import "./globals.css";
import { NextAuthProvider } from "@/app/components/SessionProvider";
import { getServerSession } from "next-auth";

export const metadata = {
    title: "Next.js",
    description: "Generated by Next.js",
};

type Props = {
    children: React.ReactNode;
};

export default async function RootLayout({ children }: Props) {
    return (
        <html lang="en">
            <body>
                <NextAuthProvider>{children}</NextAuthProvider>
            </body>
        </html>
    );
}
